# This configuration file is necessary for constants used
#  in the DynamicCraftPlugin

urls:
  test: true
  uat: https://uat.craftsilicon.com 
  live:  https://app.craftsilicon.com
  tokenUrl: /ElmaAuthDynamicV3/api/auth/app #/ElmaV4Auth/api/auth/apps

request:
  trxSource: APP
  versionNumber: 1
  bankId: "23"
  appName: HFBUG
  country: UGANDA
  bankCustomerID: "25100002"
  countryCode: "256"
  countryIsoCode: "UG"


appProperties:
  appLabel: HFBUG
  appPrimaryColor: 72CC39
  appSecondaryColor: F6D703

#  urls:
#    test: true
#    uat: https://dbsuat.visionfundmfi.com #https://uat.craftsilicon.com
#    live: https://app.craftsilicon.com
#    tokenUrl: /ElmaV4Auth/api/auth/app #ElmaAuthDynamicV3/api/auth/apps
#
#  request:
#    trxSource: APP
#    versionNumber: 1
#    bankId: "9972"
#    appName: VISIONFUND
#    country: ETHIOPIATEST
#    bankCustomerID: "25609972"
#    countryCode: "251"
#    countryIsoCode: "ET"
#
#  appProperties:
#    appLabel: Vision Fundr
#    appPrimaryColor: 293178
#    appSecondaryColor: E84910
